# Generated by Django 5.1.4 on 2024-12-05 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productmodel',
            table='product_table',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
