# Generated by Django 5.1.4 on 2024-12-06 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersmodel',
            name='buyer_id',
        ),
        migrations.RemoveField(
            model_name='ordersmodel',
            name='product_id',
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='OrdersModel',
        ),
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
